In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_excel('C:/LetsUpgrade_AI_ML/Day21/Data/Linear Regression.xlsx',sheet_name=0)

In [3]:
data.head()

price  sqft_living  bedrooms  bathrooms  floors
0  221900         1180         3       1.00     1.0
1  538000         2570         3       2.25     2.0
2  180000          770         2       1.00     1.0
3  604000         1960         4       3.00     1.0
4  510000         1680         3       2.00     1.0

In [4]:
data.dtypes

price            int64
sqft_living      int64
bedrooms         int64
bathrooms      float64
floors         float64
dtype: object

In [5]:
x=data.iloc[:,1:]

In [6]:
x

sqft_living  bedrooms  bathrooms  floors
0             1180         3       1.00     1.0
1             2570         3       2.25     2.0
2              770         2       1.00     1.0
3             1960         4       3.00     1.0
4             1680         3       2.00     1.0
...            ...       ...        ...     ...
21608         1530         3       2.50     3.0
21609         2310         4       2.50     2.0
21610         1020         2       0.75     2.0
21611         1600         3       2.50     2.0
21612         1020         2       0.75     2.0

[21613 rows x 4 columns]

In [7]:
y=data.iloc[:,:1]
y

price
0      221900
1      538000
2      180000
3      604000
4      510000
...       ...
21608  360000
21609  400000
21610  402101
21611  400000
21612  325000

[21613 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [11]:
data.shape

(21613, 5)

In [12]:
X_train.shape

(17290, 4)

In [13]:
Y_train.shape

(17290, 1)

In [14]:
X_test.shape

(4323, 4)

In [15]:
Y_test.shape

(4323, 1)

# Model Building with sklearn

In [16]:
from sklearn.linear_model import LinearRegression
mul_reg=LinearRegression()

In [17]:
mul_reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Train

In [18]:
mul_reg.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
mul_reg.coef_

array([[   309.11099034, -57550.54119311,   8440.49060067,
         -1165.39355228]])

In [20]:
mul_reg.intercept_

array([76097.63298339])

In [21]:
Y_pred=mul_reg.predict(X_test)
Y_pred

array([[608095.96846158],
       [585712.20079791],
       [416482.58364346],
       ...,
       [683810.03201802],
       [221742.65972713],
       [426849.61955589]])

In [22]:
X_test.head()

sqft_living  bedrooms  bathrooms  floors
6638         2410         4       2.25     1.5
7366         2170         3       1.50     1.0
3158         1450         2       1.00     1.0
9117         4500         5       3.25     2.0
3392          860         2       1.00     1.0

In [23]:
Y_test.head()

price
6638   735000
7366  1150000
3158   350500
9117   860000
3392   122000

# Estimate the price

In [24]:
from sklearn.metrics import mean_squared_error,r2_score
RMSE=np.sqrt(mean_squared_error(Y_test,Y_pred))
r_square=r2_score(Y_test,Y_pred)

print ("The R-square value is...",r_square)
print ("The RMSE value is...",RMSE)

The R-square value is... 0.5166693554435362
The RMSE value is... 259763.19584802483


In [28]:
unseen_pred=mul_reg.predict(np.array([[1450,2,1.00,1.0]]))
print('The unseen for the given x is....',unseen_pred)

The unseen for the given x is.... [[416482.58364346]]
