# 1. Create a 3x3x3 array with random values 

In [6]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.74973782 0.03568428 0.58506188]
  [0.60300477 0.829508   0.93159296]
  [0.04435524 0.25943179 0.08812916]]

 [[0.6378111  0.97406257 0.59978151]
  [0.25889944 0.12540458 0.38642527]
  [0.40057696 0.96627415 0.04829098]]

 [[0.92519391 0.38405231 0.94008477]
  [0.73884087 0.76911785 0.62433117]
  [0.47192218 0.75801491 0.85015446]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
import numpy as np

z = np.diag(1+np.arange(4), k=-1)
print (z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [31]:
import numpy as np
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [33]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.23907269 0.74207744 0.30476816 0.38151495 0.14400587]
 [0.82326199 0.43192313 0.4940982  0.11055626 0.33998871]
 [0.79947401 0.29565681 0.74645217 0.91910358 0.51103931]
 [0.74361314 0.65715336 0.76178352 0.977742   0.2056908 ]
 [0.77320825 0.98445725 0.56161269 0.42901358 0.05606676]]
After normalization:
[[0.19712172 0.73892472 0.26788448 0.35055098 0.09472212]
 [0.82637126 0.40484729 0.47181811 0.05869244 0.3058217 ]
 [0.80074845 0.25807034 0.74363688 0.9296054  0.49006594]
 [0.74057887 0.64745019 0.76015079 0.99276678 0.16116499]
 [0.77245674 1.         0.54454019 0.40171332 0.        ]]


# 5.  How to find common values between two arrays?

In [34]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [35]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [37]:
import numpy as np
x = np.random.randint(0,10,6)
print("First array:")
print(x)
y = np.random.randint(0,10,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[6 3 0 0 2 7]
Second array:
[1 9 6 9 1 5]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [43]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.92197711 0.50941713 0.11653089 0.70412936 0.32329566 0.30397009
 0.41119482 0.86624372 0.77620232 0.28149191]
Maximum value replaced by 0:
[0.         0.50941713 0.11653089 0.70412936 0.32329566 0.30397009
 0.41119482 0.86624372 0.77620232 0.28149191]


# 9. How to print all the values of an array?

In [13]:
i = np.array([[1,2,11],[3,4,10],[4,5,6]])
print(i)

#print ('Max Value is ',i.max())

print(i.shape)

for x in (range(i.shape[0])):
    print('Values in ',x,' row')
    for y in (range(i.shape[1])):
              print (i[x][y])

[[ 1  2 11]
 [ 3  4 10]
 [ 4  5  6]]
(3, 3)
Values in  0  row
1
2
11
Values in  1  row
3
4
10
Values in  2  row
4
5
6


# 10.Subtract the mean of each row of a matrix

In [47]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.70078139 0.37505096 0.60298279 0.52110077 0.74845792 0.89235808
  0.78528991 0.85965206 0.22184681 0.00900827]
 [0.3548503  0.24895818 0.49979452 0.53708123 0.6439413  0.87135348
  0.63289233 0.61753424 0.95433724 0.32329799]
 [0.87859329 0.00173786 0.2532424  0.21067496 0.32806552 0.085
  0.66905535 0.18832245 0.74204031 0.87431047]
 [0.37978233 0.89942535 0.89266205 0.22708033 0.94569766 0.08194359
  0.55360949 0.78583988 0.38276891 0.67432849]
 [0.62545517 0.70619668 0.71107147 0.90089676 0.25778216 0.95000225
  0.64670687 0.57567141 0.31374666 0.30652486]]

Subtract the mean of each row of the said matrix:

[[ 0.12912849 -0.19660193  0.0313299  -0.05055213  0.17680503  0.32070519
   0.21363702  0.28799916 -0.34980609 -0.56264463]
 [-0.21355378 -0.3194459  -0.06860956 -0.03132285  0.07553722  0.3029494
   0.06448825  0.04913016  0.38593316 -0.24510609]
 [ 0.45548903 -0.4213664  -0.16986186 -0.2124293  -0.09503874 -0.33810426
   0.24595109 -0.23478181  0.3189360

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [16]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 2. 3. 2. 2. 6. 4. 3. 2. 5.]


# 12.How to get the diagonal of a dot product?

In [54]:
a = np.arange(9).reshape(3, 3)
b = np.arange(9).reshape(3, 3)

x = np.dot(a, b)
print (x)
np.diag(np.dot(a, b))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


array([ 15,  54, 111])

# 13.How to find the most frequent value in an array?

In [55]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[4 5 4 9 2 4 2 9 6 7 3 9 3 1 7 1 0 2 7 9 0 0 9 4 6 3 2 6 7 9 2 3 4 3 8 6 8
 1 2 7]
Most frequent value in the above array:
2


# 14.How to get the n largest values of an array

In [58]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 4
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]


# 15.How to create a record array from a regular array?

In [20]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3])
print(result[0])
print(result[1])
print(result[2])
print(result[3])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
(4, 'Orange', 40.)
